### ISSUE TITLE
Properly report DNSLink errors vs other namesys errors

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-namesys#11]
https://github.com/ipfs/go-namesys/pull/9 introduced a bug where it assumes many namesys errors are DNSLink errors (e.g. trying to download IPNS records when offline results in a failure that is reported as a DNSLink error instead of an IPNS error)

This PR should either be reverted (resulting in less precise DNSLink errors) or we should fix the error reporting so we keep the more precise DNSLink errors, but only when it's actually a DNSLink error.

**Comment by lidel** [comment]
Closed in https://github.com/ipfs/go-namesys/pull/12
