### ISSUE TITLE
Don't write byte arrays into the logs?

### ISSUE THREAD

**Issue by achingbrain** [ipfs/go-namesys#22]
It occasionally makes debugging hard:

![image](https://user-images.githubusercontent.com/665810/137080194-20af299b-1ab1-4c1f-af0a-50f0198ec155.png)

The offending line is [here](https://github.com/ipfs/go-namesys/blob/master/publisher.go#L287)

**Comment by laurentsenta** [comment]
(the line moved, permalink: https://github.com/ipfs/go-namesys/blob/9f5f653207b1e2ba05f5fdbb1d1deb6e0a7a3f67/publisher.go#L277)
