### ISSUE TITLE
Study removing dependency on interface-go-ipfs-core

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-namesys#6]
The namesys options are part of https://github.com/ipfs/interface-go-ipfs-core .

See https://github.com/ipfs/interface-go-ipfs-core/tree/master/options/namesys

This is a dependency that we could remove by bringing options over to this repository.

**Comment by Stebalien** [comment]
Moving these options from interface-go-ipfs-core in such a way that makes interface-go-ipfs-core depend on this package is not an option. I'm not sure what the correct approach is, but that's definitely not it (it makes the interface package depend on things like the DHT).

**Comment by Stebalien** [comment]
Well, after fixing https://github.com/ipfs/go-namesys/issues/5, that issue would go away. But still, an interface package should never depend on a service implementation package.
